# TODO: support docker-user: auto
# This will pull the last user command from your Dockerfile or default to root
# Or can be overridden at the cli
docker-user: docker

target_services:
  adcdc:
    # Location of dev dockerfile, relative paths will be parsed by this config file's location.
    # This allows you to store this config & your dev-dockerfile in the same directory
    dev-dockerfile: ./Dockerfile

    ###################################################################################
    # ${DOCKERUSER} is supported for any of the following config items
    # This will be auto-replaced by the docker-user config item defined above
    ###################################################################################

    # Any shell command works: /bin/zsh or /home/${DOCKERUSER}/.local/bin/fish or /opt/alacritty -e /usr/bin/tmux
    # To change the working dir, set that in your dev-dockerfile
    command: /bin/bash

    # Determines how to mount your code directory in the dockerfile
    # Filepaths should be relative to your codes pwd
    code-mount: .:/home/${DOCKERUSER}/code

    # Additional volues for configs or other things. This is mainly used to mount your .configs in the container
    volumes:
      # Generally absolute paths are best. Relative filepaths are relative to your code's pwd
      - ./examples/lunarvim/config.lua:/home/${DOCKERUSER}/.config/lvim/config.lua
      - ./examples/lunarvim/userconfig.lua:/home/${DOCKERUSER}/.config/lvim/lua/userconfig.lua

